-- Sibling creative branches on a proposal chain (2026-08-16).
--
-- Generated by `prisma migrate diff --from-config-datasource --to-schema`.
-- Its output also contained `DROP TABLE "playing_with_neon"` — a leftover
-- Neon sample table that is not in schema.prisma and has nothing to do with
-- this change. Deliberately excluded: a migration should do the one thing it
-- is named after, and dropping an unrelated table as a side effect is how a
-- routine deploy becomes an incident.
--
-- Both columns are nullable, so every existing row stays valid and no
-- backfill is required: branchOfProposalId IS NULL already means "this is an
-- original", which is true of every proposal written before today.
ALTER TABLE "ApprovalRequest" ADD COLUMN     "branchLabel" TEXT,
ADD COLUMN     "branchOfProposalId" TEXT;
