import { existsSync } from "fs";
import * as dotenv from "dotenv";

// ONE-TIME PROMOTION: brandIdentity's four claims → business facts.
//
//   npx tsx scripts/promote-brand-claims.ts            report only, writes nothing
//   npx tsx scripts/promote-brand-claims.ts --apply    writes
//   npx tsx scripts/promote-brand-claims.ts --apply --store <id>
//
// WHY THIS IS A SCRIPT AND NOT A MIGRATION. It changes data, not shape, and this
// repository's migration chain runs against production on every push with no
// review step (see the migration-gate note in DEPLOYMENT.md). A one-time data
// promotion belongs somewhere a person decides to run it, once, having read what
// it would do. It is also trivially reversible — every row it writes carries
// provenanceDetail "promoted_from_blueprint".
//
// WHAT IT DOES. D1-A moved four fields out of Store.blueprint.brandIdentity and
// into owner-authoritative entity types. New businesses get them at onboarding
// and whenever the owner states them. EXISTING businesses have values sitting in
// the blueprint that nothing reads any more — so without this, J4 silently stops
// knowing who an existing business is for.
//
// PROVENANCE IS **INFERENCE**, AND THAT IS THE WHOLE CARE OF THIS SCRIPT.
//
// These values were generated by a model during onboarding or a content turn.
// Nobody stated them. Writing them as OWNER would fabricate testimony — it would
// put words in an owner's mouth and make them indistinguishable from something
// they actually said, which is precisely the confusion D1-A exists to end.
// RecordProvenance.INFERENCE is exactly this case: "J4 concluded it… nothing
// outside this system asserted it… never to be presented, weighed, or spoken
// about as though somebody had said it."
//
// And it upgrades cleanly: when the owner later states their audience, that
// statement supersedes the inference through the ordinary fact lifecycle, with
// history preserved. An inference becoming testimony is the correct direction.
//
// SAFEGUARDS
//   - dry run by default; --apply is required to write
//   - never overwrites: a store that already has a current fact of that type is
//     skipped, so re-running is safe and cannot clobber an owner's own words
//   - blank values are skipped rather than written as empty facts
//   - the blueprint is NOT modified; the old values stay where they are

// AN ENV FILE, NOT AN INLINE CONNECTION STRING (2026-08-25).
//
// This script is meant to be pointed at PRODUCTION, and without this it silently
// used the ambient .env — i.e. the dev database — while looking like it had run.
// Same argument and the same reasoning as check-stripe-live-readiness.ts: naming
// a file keeps a live connection string out of shell history, and out of a
// terminal that treats `&` in a Postgres URL as an operator.
//
//   npx tsx scripts/promote-brand-claims.ts prod.env
//   npx tsx scripts/promote-brand-claims.ts prod.env --apply
const envFile = process.argv[2] && !process.argv[2].startsWith("--") ? process.argv[2] : null;
if (envFile) {
  if (!existsSync(envFile)) {
    console.error(`No such env file: ${envFile}`);
    process.exit(1);
  }
  dotenv.config({ path: envFile, override: true });
  console.log(`Loaded environment from: ${envFile}`);
} else {
  dotenv.config();
  console.log("No env file named — using the ambient environment (probably dev).");
}

const APPLY = process.argv.includes("--apply");
const ONE_STORE = (() => {
  const i = process.argv.indexOf("--store");
  return i >= 0 ? process.argv[i + 1] : null;
})();

/** blueprint key → entity type. */
const PROMOTIONS = [
  ["targetAudience", "targetAudience"],
  ["brandPersonality", "brandPersonality"],
  ["brandVoiceAndTone", "brandVoice"],
  ["uniqueSellingProposition", "sellingProposition"],
] as const;

async function main() {
  const { prisma } = await import("@/lib/prisma");
  const { currentFacts } = await import("@/lib/businessModel/factLifecycle");
  const { persistSyncedRecords } = await import("@/lib/businessModel/sync");

  const stores = await prisma.store.findMany({
    where: ONE_STORE ? { id: ONE_STORE } : {},
    select: { id: true, name: true, blueprint: true },
  });

  console.log(`\n${APPLY ? "APPLYING" : "DRY RUN — nothing will be written"}`);
  console.log(`${stores.length} store(s) to consider\n`);

  let wrote = 0;
  let skippedExisting = 0;
  let skippedBlank = 0;

  for (const store of stores) {
    const identity = (store.blueprint as { brandIdentity?: Record<string, unknown> } | null)
      ?.brandIdentity;
    if (!identity) continue;

    for (const [blueprintKey, entityType] of PROMOTIONS) {
      const raw = identity[blueprintKey];
      const statement = typeof raw === "string" ? raw.trim() : "";
      if (!statement) {
        skippedBlank++;
        continue;
      }

      // NEVER OVERWRITE. If a current fact exists, the owner or a later process
      // has already answered this — a promotion from a stale blueprint must not
      // supersede it.
      const existing = await currentFacts(store.id, entityType);
      if (existing.length > 0) {
        skippedExisting++;
        continue;
      }

      console.log(`  ${store.name} · ${entityType}: ${statement.slice(0, 60)}`);
      if (!APPLY) {
        wrote++;
        continue;
      }

      await persistSyncedRecords(
        store.id,
        "genesis_promotion",
        [{ entityType, externalId: `promoted:${entityType}`, data: { statement } }],
        {
          // INFERENCE, not OWNER. Nobody said this; a model produced it.
          provenance: "INFERENCE",
          provenanceDetail: "promoted_from_blueprint",
          modelExtracted: true,
        }
      );
      wrote++;
    }
  }

  console.log(`\n${APPLY ? "wrote" : "would write"}: ${wrote}`);
  console.log(`skipped, a current fact already exists: ${skippedExisting}`);
  console.log(`skipped, blank in the blueprint: ${skippedBlank}`);
  if (!APPLY) console.log(`\nRe-run with --apply to write. Nothing was changed.`);
  process.exit(0);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
