// A REAL AES-256 KEY FOR THIS PROCESS, set before anything imports the
// credential helper — the same thing verify-credential-encryption.ts does, and
// for the same reason. The seed is genuinely encrypted with the genuine
// algorithm here; nothing about production encryption is weakened or bypassed.
// Set at module scope because getKey() reads env at call time and the imports
// below reach it.
process.env.INTEGRATION_ENCRYPTION_KEY =
  process.env.INTEGRATION_ENCRYPTION_KEY ?? Buffer.alloc(32, 11).toString("base64");

import { generateSync } from "otplib";
import { requireTestDatabase } from "@/scripts/lib/requireTestDatabase";
import { prisma, prismaSystem } from "@/lib/prisma";
import {
  beginTwoFactorSetup,
  enableTwoFactor,
  disableTwoFactor,
  isTwoFactorEnabled,
  isCodeValid,
  verifySecondFactor,
  regenerateRecoveryCodes,
  countUnusedRecoveryCodes,
  RECOVERY_CODE_COUNT,
} from "@/lib/security/twoFactor";
import { SECURITY_EVENTS } from "@/lib/security/events";

// TWO-FACTOR AUTHENTICATION, WITH A REAL CODE:
//
//   npx tsx scripts/run-db-suites.ts two-factor
//
// The 2026-08-06 scoping set the bar for this milestone and it stands: enable
// -> produce a genuine code -> verify -> recovery codes work -> disable ->
// re-enable. Every code below is generated by the same TOTP algorithm an
// authenticator app runs, from the seed this module actually stored, so nothing
// here is asserted against a stub.
//
// ENROLMENT AND RECOVERY ARE ONE FEATURE. Threat case T5 — a lost phone — is by
// volume the likeliest real incident once 2FA exists, more common than the
// phished password it defends against. Shipping enrolment without recovery
// would mean the first owner to lose a phone loses their business.
//
// THE SEED IS A BEARER SECRET. §5 asserts it is encrypted at rest, because a
// database leak that included it would be a leak of everyone's second factor —
// and because "we store the TOTP secret" is the kind of thing that is true in a
// design document and false in the table.

const results: { name: string; ok: boolean; detail: string }[] = [];
function check(name: string, actual: unknown, expected: unknown) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  results.push({ name, ok, detail: "" });
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}`);
  if (!ok) console.log(`        expected ${JSON.stringify(expected)}\n        actual   ${JSON.stringify(actual)}`);
}
function assert(name: string, ok: boolean, detail = "") {
  results.push({ name, ok, detail });
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? `  — ${detail}` : ""}`);
}

async function main() {
  await requireTestDatabase(prismaSystem);

  const owner = await prisma.user.create({
    data: { email: `tfa-${Math.random().toString(36).slice(2)}@test.local`, name: "Owner" },
  });

  try {
    // ========================================================================
    console.log("\n=== 1. A secret alone is not protection ===\n");
    // ========================================================================
    check("an account starts with 2FA off", await isTwoFactorEnabled(owner.id), false);

    const setup = await beginTwoFactorSetup({ userId: owner.id, accountEmail: owner.email });
    assert("setup produces a secret", typeof setup.secret === "string" && setup.secret.length >= 16,
      String(setup.secret?.length));
    assert("and a URI an authenticator app can scan", setup.uri.startsWith("otpauth://totp/"), setup.uri.slice(0, 60));
    assert("naming Genesis as the issuer", setup.uri.includes("issuer=Genesis"), setup.uri);
    assert("and the account it belongs to", setup.uri.includes(encodeURIComponent(owner.email).replace(/%40/g, "%40")),
      setup.uri);

    // THE ASSERTION THAT PREVENTS A LOCKOUT. A stored seed with no verified
    // code is an abandoned setup, and treating it as enabled would demand a
    // factor the owner never proved they had.
    check("a stored secret does NOT mean 2FA is on", await isTwoFactorEnabled(owner.id), false);
    assert(
      "so an abandoned setup never locks anybody out",
      (await isTwoFactorEnabled(owner.id)) === false,
      "enabling on a seed nobody has verified demands a factor they may not hold"
    );

    // ========================================================================
    console.log("\n=== 2. A real code from the real algorithm ===\n");
    // ========================================================================
    const realCode = generateSync({ secret: setup.secret });
    assert("the code is six digits", /^\d{6}$/.test(realCode), realCode);
    check("and it validates against the seed", isCodeValid(realCode, setup.secret), true);
    check("a wrong code does not", isCodeValid("000000", setup.secret), false);
    check("nor does a non-numeric one", isCodeValid("ABCDEF", setup.secret), false);
    check("nor the wrong length", isCodeValid("12345", setup.secret), false);

    // Authenticator apps DISPLAY the code with a space in the middle. Refusing
    // what the owner reads off their phone would be refusing the right answer.
    check("a code typed with the space the app shows still works",
      isCodeValid(`${realCode.slice(0, 3)} ${realCode.slice(3)}`, setup.secret), true);

    // ========================================================================
    console.log("\n=== 3. Enabling requires proving you can produce one ===\n");
    // ========================================================================
    const refused = await enableTwoFactor({ userId: owner.id, token: "000000" });
    check("a wrong code does not enable it", refused, { enabled: false, reason: "incorrect_code" });
    check("and 2FA is still off", await isTwoFactorEnabled(owner.id), false);

    const enabled = await enableTwoFactor({ userId: owner.id, token: generateSync({ secret: setup.secret }) });
    assert("a real code enables it", enabled.enabled, JSON.stringify(enabled));
    check("and it is now genuinely on", await isTwoFactorEnabled(owner.id), true);

    // RECOVERY CODES ARRIVE WITH ENROLMENT, not as a later step.
    const codes = enabled.enabled ? enabled.recoveryCodes : [];
    check("a full set of recovery codes is issued", codes.length, RECOVERY_CODE_COUNT);
    assert("each is unique", new Set(codes).size === codes.length, codes.join(" "));
    assert("and readable enough to write down",
      codes.every((c) => /^[A-Z2-9]{5}-[A-Z2-9]{5}$/.test(c)), codes[0]);
    // Written on paper in a hurry and typed back months later under stress.
    assert("with no characters anybody confuses",
      codes.every((c) => !/[O0I1LU]/.test(c)), codes.join(" "));

    // ========================================================================
    console.log("\n=== 4. The challenge: a code, or a recovery code, once ===\n");
    // ========================================================================
    const passed = await verifySecondFactor({ userId: owner.id, token: generateSync({ secret: setup.secret }) });
    assert("a real code passes the challenge", passed.passed, JSON.stringify(passed));
    check("and is not counted as a recovery code",
      passed.passed ? passed.usedRecoveryCode : null, false);

    const wrong = await verifySecondFactor({ userId: owner.id, token: "000000" });
    check("a wrong one is refused", wrong, { passed: false, reason: "incorrect" });

    // A RECOVERY CODE WORKS EXACTLY ONCE. This is threat case T5's whole
    // answer, and spending one twice would turn a paper backup into a
    // permanent bypass.
    const recovery = codes[0];
    const first = await verifySecondFactor({ userId: owner.id, token: recovery });
    assert("a recovery code passes", first.passed, JSON.stringify(first));
    check("and is reported as one", first.passed ? first.usedRecoveryCode : null, true);
    check("leaving one fewer", first.passed ? first.recoveryCodesRemaining : null, RECOVERY_CODE_COUNT - 1);

    const reused = await verifySecondFactor({ userId: owner.id, token: recovery });
    check("the same code does not work twice", reused, { passed: false, reason: "incorrect" });
    check("and the count did not move again", await countUnusedRecoveryCodes(owner.id), RECOVERY_CODE_COUNT - 1);
    assert(
      "so a paper backup is a one-time way in, not a permanent bypass",
      reused.passed === false,
      "claimed with a conditional update, so two concurrent attempts cannot both spend it"
    );

    // Case and spacing, because these are transcribed by hand.
    const second = await verifySecondFactor({ userId: owner.id, token: codes[1].toLowerCase() });
    assert("a recovery code typed in lower case still works", second.passed, JSON.stringify(second));

    // ========================================================================
    console.log("\n=== 5. The seed is encrypted at rest ===\n");
    // ========================================================================
    // "We store the TOTP secret encrypted" is the kind of claim that is true in
    // a design document and false in the table. Read the column directly.
    const row = await prisma.user.findUniqueOrThrow({
      where: { id: owner.id },
      select: { totpSecret: true },
    });
    assert("the seed column holds something", Boolean(row.totpSecret));
    assert(
      "and it is NOT the seed in plain text",
      !row.totpSecret?.includes(setup.secret),
      "anyone holding this can mint valid codes forever"
    );
    assert("it is the same encrypted envelope integration credentials use",
      row.totpSecret?.includes("encrypted:1") === true, String(row.totpSecret).slice(0, 40));

    // Recovery codes are hashed exactly like passwords.
    const stored = await prisma.recoveryCode.findMany({ where: { userId: owner.id } });
    assert("no recovery code is stored in plain text",
      stored.every((s) => !codes.includes(s.codeHash)), "a table of usable codes is a table of passwords");
    assert("they are bcrypt hashes", stored.every((s) => s.codeHash.startsWith("$2")), stored[0]?.codeHash.slice(0, 4));

    // ========================================================================
    console.log("\n=== 6. Regenerating invalidates everything before it ===\n");
    // ========================================================================
    const fresh = await regenerateRecoveryCodes({ userId: owner.id });
    check("a full new set is issued", fresh.length, RECOVERY_CODE_COUNT);
    check("and all of them are unused", await countUnusedRecoveryCodes(owner.id), RECOVERY_CODE_COUNT);
    assert("they are genuinely different codes",
      fresh.every((c) => !codes.includes(c)), "regenerating exists because the old ones are believed compromised");

    const oldOne = await verifySecondFactor({ userId: owner.id, token: codes[2] });
    check("an old code no longer works", oldOne, { passed: false, reason: "incorrect" });

    // ========================================================================
    console.log("\n=== 7. Off, and on again ===\n");
    // ========================================================================
    await disableTwoFactor({ userId: owner.id });
    check("2FA is off", await isTwoFactorEnabled(owner.id), false);
    check("every recovery code is gone with it", await countUnusedRecoveryCodes(owner.id), 0);
    assert(
      "so re-enabling cannot silently accept a phone the owner already wiped",
      (await prisma.user.findUniqueOrThrow({ where: { id: owner.id }, select: { totpSecret: true } })).totpSecret === null,
      "the seed goes too, not just the flag"
    );

    const challengeAfterOff = await verifySecondFactor({ userId: owner.id, token: generateSync({ secret: setup.secret }) });
    check("and the old seed no longer passes a challenge", challengeAfterOff, { passed: false, reason: "not_enrolled" });

    // Full round trip, which is the bar the scoping set.
    const again = await beginTwoFactorSetup({ userId: owner.id, accountEmail: owner.email });
    assert("a new setup issues a DIFFERENT seed", again.secret !== setup.secret, "or disabling would be cosmetic");
    const reEnabled = await enableTwoFactor({ userId: owner.id, token: generateSync({ secret: again.secret }) });
    assert("and it can be enabled again", reEnabled.enabled, JSON.stringify(reEnabled));
    check("with a fresh set of recovery codes",
      reEnabled.enabled ? reEnabled.recoveryCodes.length : 0, RECOVERY_CODE_COUNT);

    // ========================================================================
    console.log("\n=== 8. Every step is in the account's history ===\n");
    // ========================================================================
    const events = await prisma.securityEvent.findMany({ where: { userId: owner.id } });
    const kinds = events.map((e) => e.kind);
    for (const [label, kind] of [
      ["turning it on", SECURITY_EVENTS.twoFactorEnabled],
      ["turning it off", SECURITY_EVENTS.twoFactorDisabled],
      ["a wrong code", SECURITY_EVENTS.twoFactorChallengeFailed],
      ["using a recovery code", SECURITY_EVENTS.recoveryCodeUsed],
      ["regenerating them", SECURITY_EVENTS.recoveryCodesRegenerated],
    ] as const) {
      assert(`${label} is recorded`, kinds.includes(kind), kinds.join(", "));
    }

    // AND NOTHING RECORDED IS A SECRET.
    const serialised = JSON.stringify(events);
    assert("no seed reached the history", !serialised.includes(setup.secret) && !serialised.includes(again.secret));
    assert("and no recovery code did either",
      ![...codes, ...fresh].some((c) => serialised.includes(c)),
      "the history is read by an owner, and stored beside the thing it audits");
    // ========================================================================
    console.log("\n=== 9. The gate at sign-in is not bypassable ===\n");
    // ========================================================================
    // THE INVARIANT THAT MAKES 2FA REAL rather than decorative. Enforced in
    // auth.ts's authorize, which is the single gate every credential sign-in
    // passes through — there is no partially authenticated state that can read
    // anything, no "skip for now", and no query parameter that reaches past it.
    // A session simply does not exist until the factor is satisfied.
    //
    // Asserted structurally, because the alternative is a full browser sign-in
    // against an account whose TOTP code changes every 30 seconds — and what
    // would actually break here is the ORDER of the checks, which is readable.
    const authSource = (await import("fs")).readFileSync("auth.ts", "utf8");

    // Matches the GUARD, not merely a mention. The first version tested for
    // `isTwoFactorEnabled(user.id)` anywhere in the file, which also matches
    // the claim written onto the returned user — so with the gate deleted
    // entirely this assertion still passed, and only the ordering checks below
    // caught it.
    assert(
      "the second factor GUARDS the sign-in, rather than merely being consulted",
      /if \(await isTwoFactorEnabled\(user\.id\)\) \{/.test(authSource),
      "anywhere else and there is a moment where a session exists without it"
    );
    assert(
      "and it refuses when no code was supplied",
      /if \(!token\) \{[\s\S]{0,400}?return null;/.test(authSource),
      "a missing code must not fall through to a successful sign-in"
    );
    assert(
      "and when the code is wrong",
      /if \(!challenge\.passed\) \{[\s\S]{0,300}?return null;/.test(authSource),
      "the challenge result has to be acted on, not merely computed"
    );

    // THE ORDER. The factor is checked AFTER the password and BEFORE the
    // session is returned. Checked before the password, it would tell an
    // attacker with no password whether an account has 2FA; checked after the
    // return, it would not be a gate at all.
    const passwordAt = authSource.indexOf("bcrypt.compare");
    const factorAt = authSource.indexOf("if (await isTwoFactorEnabled(user.id)) {");
    const returnAt = authSource.indexOf("return { ...user,");
    assert("the password is verified first", passwordAt > 0 && passwordAt < factorAt,
      `password ${passwordAt}, factor ${factorAt}`);
    assert("then the second factor", factorAt > 0 && factorAt < returnAt,
      `factor ${factorAt}, return ${returnAt}`);
    assert(
      "so no session is ever minted before the factor is satisfied",
      passwordAt < factorAt && factorAt < returnAt,
      "checked after the return it is not a gate; checked before the password it is an oracle"
    );

    // Refused identically to a wrong password, so a stolen password cannot be
    // confirmed as correct by watching the response change.
    assert(
      "a missing code is refused the same way a wrong password is",
      authSource.split("return null;").length > 4,
      "a distinct answer would tell somebody holding a stolen password they only needed the phone"
    );
  } finally {
    await prisma.user.delete({ where: { id: owner.id } }).catch(() => {});
  }

  const failed = results.filter((r) => !r.ok);
  console.log(`\n${results.length - failed.length}/${results.length} passed`);
  if (failed.length > 0) process.exitCode = 1;
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
